import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

/// Renders a DICT_4X4_1000 ArUco marker from bundled PNG assets.
///
/// The PNG bundle is generated by `scripts/generate_aruco_markers.py` and
/// lives at `assets/markers/aruco_4x4_1000/{id}.png`. When the asset is
/// missing — e.g., the script hasn't been run yet, or the assets directory
/// isn't declared in pubspec.yaml — we render a labelled placeholder so the
/// rest of the add-dog flow keeps working.
class ArucoMarkerView extends StatelessWidget {
  final int markerId;
  final double size;

  const ArucoMarkerView({
    super.key,
    required this.markerId,
    this.size = 200,
  });

  String get _assetPath => 'assets/markers/aruco_4x4_1000/$markerId.png';

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: Colors.black, width: 1),
      ),
      child: Image.asset(
        _assetPath,
        fit: BoxFit.contain,
        filterQuality: FilterQuality.none, // preserve sharp marker edges
        errorBuilder: (context, error, stackTrace) => _Placeholder(
          markerId: markerId,
          size: size,
        ),
      ),
    );
  }
}

/// Loads the marker PNG bytes for printing/sharing. Returns null if the
/// asset isn't bundled yet.
Future<Uint8List?> loadArucoMarkerBytes(int markerId) async {
  try {
    final data = await rootBundle.load(
      'assets/markers/aruco_4x4_1000/$markerId.png',
    );
    return data.buffer.asUint8List();
  } catch (_) {
    return null;
  }
}

class _Placeholder extends StatelessWidget {
  final int markerId;
  final double size;

  const _Placeholder({required this.markerId, required this.size});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      color: Colors.grey.shade200,
      alignment: Alignment.center,
      padding: const EdgeInsets.all(12),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.qr_code_2,
              size: size * 0.3, color: Colors.grey.shade500),
          const SizedBox(height: 8),
          Text(
            'ID $markerId',
            style: const TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 18,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            'Marker bundle not generated.\nSee scripts/generate_aruco_markers.py',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 10, color: Colors.grey.shade700),
          ),
        ],
      ),
    );
  }
}
