import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// LIVE Firebase config for project `wimzpushy` (generated by
/// `flutterfire configure` 2026-07-30) — push notifications are active.
/// These are client identifiers, not secrets (standard practice to commit).
/// Regenerate with `flutterfire configure --project=wimzpushy` if apps are
/// added or keys rotate; PushService soft-disables only if the apiKey ever
/// reads 'PLACEHOLDER' again.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web push is not configured for WIM-Z.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'Push is not supported on $defaultTargetPlatform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh2UDW7t6iUdDLxCiIpx5olWFULpTywl4',
    appId: '1:7574615146:android:2e2606a2f23a723bb1c613',
    messagingSenderId: '7574615146',
    projectId: 'wimzpushy',
    storageBucket: 'wimzpushy.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvKcZ9mVrzVa4wMOlphwXI1mnII3tMy8',
    appId: '1:7574615146:ios:7b2747417aba945cb1c613',
    messagingSenderId: '7574615146',
    projectId: 'wimzpushy',
    storageBucket: 'wimzpushy.firebasestorage.app',
    iosBundleId: 'com.wimzai.app',
  );
}
